server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: services
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: name
            values: [user]
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
    pipeline_stages:
      - docker: {}